// FROZEN LEGACY DATA — hand-entered history predating posted-card JSON.
// Cutoff: days strictly before 2026-05-23. Extracted once from the
// original RecordTracker.jsx. Safe to edit by hand if you ever correct a
// historical box score; the generator never touches this file.

export const LEGACY_RESULTS = [
  {
    date:  "2026-05-22",
    sport: "MLB",
    plays: [
      {player:"Davis Martin",       prop:"K OVER 4.5",  odds:-153, tier:"AUTO", hit:true,  actual:7,    note:"CWS @ SF — 7 Ks, WIN +$65.36"},
      {player:"Ezequiel Tovar",     prop:"H OVER 0.5",  odds:-148, tier:"T1",   hit:true,  actual:2,    note:"COL @ ARI — 2 hits, WIN +$67.57"},
      {player:"Richie Palacios",    prop:"H OVER 0.5",  odds:-145, tier:"T1",   hit:true,  actual:1,    note:"TB @ NYY — 1 hit, WIN +$68.97"},
      {player:"Brandon Valenzuela", prop:"H OVER 0.5",  odds:-125, tier:"AUTO", hit:false, actual:0,    note:"STL @ CIN — 0 hits, LOSS"},
      {player:"Brett Baty",         prop:"H OVER 0.5",  odds:-140, tier:"T1",   hit:false, actual:0,    note:"NYM @ MIA — 0 hits, LOSS"},
      {player:"Jesus Sanchez",      prop:"H OVER 0.5",  odds:-147, tier:"T1",   hit:"void", actual:null, note:"PPD — VOID"},
      {player:"Josh Lowe",          prop:"H OVER 0.5",  odds:-115, tier:"T1",   hit:"void", actual:null, note:"DNP — VOID"},
      {player:"Cristopher Sanchez", prop:"K OVER 6.5",  odds:-120, tier:"T1",   hit:"void", actual:null, note:"PPD — VOID"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-21",
    sport: "MLB",
    plays: [
      {player:"Konnor Griffin", prop:"H OVER 0.5",  odds:105,  tier:"AUTO", hit:true,  actual:1, note:"PIT @ STL — 1 hit, WIN +$105"},
      {player:"Daulton Varsho", prop:"H OVER 0.5",  odds:-157, tier:"AUTO", hit:true,  actual:1, note:"TOR @ NYY — 1 hit, WIN +$63.69"},
      {player:"Keibert Ruiz",   prop:"H OVER 0.5",  odds:-177, tier:"AUTO", hit:true,  actual:2, note:"WSH home — 2 hits, WIN +$56.50"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-20",
    sport: "MLB",
    plays: [
      {player:"Shohei Ohtani",  prop:"K OVER 6.5",  odds:-135, tier:"AUTO", hit:false, actual:4,    note:"LAD @ SD — 4 Ks on 6.5 line, LOSS (grader matched wrong prop initially)"},
      {player:"Jake Bauers",    prop:"H OVER 0.5",  odds:-126, tier:"AUTO", hit:true,  actual:1,    note:"MIL @ CHC — 1 hit, WIN +$79.37"},
      {player:"Cedric Mullins", prop:"H OVER 0.5",  odds:-139, tier:"AUTO", hit:false, actual:0,    note:"BAL @ TB — 0 hits, LOSS"},
      {player:"Nolan Gorman",   prop:"H OVER 0.5",  odds:-146, tier:"AUTO", hit:false, actual:0,    note:"PIT @ STL — 0 hits, LOSS"},
      {player:"Kyle Isbel",     prop:"H OVER 0.5",  odds:-126, tier:"AUTO", hit:false, actual:0,    note:"KC @ BOS — 0 hits, LOSS"},
      {player:"Jesus Sanchez",  prop:"H OVER 0.5",  odds:-133, tier:"T1",   hit:"void", actual:null, note:"Not in lineup — VOID"},
      {player:"Kyle Manzardo",  prop:"H OVER 0.5",  odds:-150, tier:"T1",   hit:false, actual:0,    note:"CLE @ DET — 0 hits, LOSS"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-19",
    sport: "MLB",
    plays: [
      {player:"Nolan McLean",   prop:"K OVER 5.5",  odds:-150, tier:"AUTO", hit:false, actual:5,    note:"NYM @ WSH — 5 Ks, needed 6, LOSS"},
      {player:"Landen Roupp",   prop:"K OVER 4.5",  odds:-138, tier:"AUTO", hit:false, actual:3,    note:"SF @ ARI — 3 Ks, streak broken, LOSS"},
      {player:"Will Warren",    prop:"K OVER 5.5",  odds:115,  tier:"AUTO", hit:false, actual:3,    note:"TOR @ NYY — 3 Ks, LOSS"},
      {player:"Samuel Basallo", prop:"H OVER 0.5",  odds:-135, tier:"AUTO", hit:false, actual:0,    note:"BAL @ TB — 0 hits, LOSS"},
      {player:"Jake Bauers",    prop:"H OVER 0.5",  odds:-135, tier:"AUTO", hit:true,  actual:2,    note:"MIL @ CHC — 2 hits, WIN +$74.07"},
      {player:"Taylor Walls",   prop:"H OVER 0.5",  odds:105,  tier:"AUTO", hit:false, actual:0,    note:"BAL @ TB — 0 hits, LOSS"},
      {player:"Michael Busch",  prop:"H OVER 0.5",  odds:-150, tier:"AUTO", hit:false, actual:0,    note:"MIL @ CHC — 0 hits, LOSS"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-18",
    sport: "MLB",
    plays: [
      {player:"Max Meyer",          prop:"K OVER 4.5",  odds:-125, tier:"AUTO", hit:true,  actual:6,    note:"ATL @ MIA — 6 Ks over 4.5, WIN +$80.00"},
      {player:"Taylor Walls",       prop:"H OVER 0.5",  odds:-105, tier:"AUTO", hit:true,  actual:2,    note:"BAL @ TB — 2 hits, WIN +$95.24"},
      {player:"Teoscar Hernandez",  prop:"H OVER 0.5",  odds:-140, tier:"AUTO", hit:false, actual:0,    note:"LAD @ SD — 0 hits, LOSS"},
      {player:"Gavin Sheets",       prop:"H OVER 0.5",  odds:-150, tier:"AUTO", hit:false, actual:0,    note:"CWS @ SEA — 0 hits, LOSS (Sheets on SD not CWS — roster error)"},
      {player:"Kody Clemens",       prop:"H OVER 0.5",  odds:-135, tier:"AUTO", hit:false, actual:0,    note:"CIN @ PHI — 0 hits, LOSS"},
      {player:"Travis Bazzana",     prop:"H OVER 0.5",  odds:-135, tier:"T1",   hit:true,  actual:2,    note:"CLE @ DET — 2 hits, WIN +$74.07"},
      {player:"Nick Fortes",        prop:"H OVER 0.5",  odds:-140, tier:"T1",   hit:false, actual:0,    note:"MIA vs ATL — 0 hits in 16-run game, LOSS"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-17",
    sport: "MLB",
    plays: [
      {player:"Paul Skenes",      prop:"K OVER 6.5",  odds:-142, tier:"AUTO", hit:true,   actual:7,    note:"PHI @ PIT — 7 Ks in 5 IP, WIN +$70.42"},
      {player:"Alejandro Osuna",  prop:"H OVER 0.5",  odds:-120, tier:"T1",   hit:true,   actual:1,    note:"BAL @ WSH — 1 hit, WIN +$83.33"},
      {player:"Aaron Judge",      prop:"TB OVER 1.5", odds:105,  tier:"T1",   hit:false,  actual:0,    note:"NYY @ NYM — 0-for-4 with walk, LOSS"},
      {player:"Luis Torrens",     prop:"H OVER 0.5",  odds:-140, tier:"T1",   hit:true,   actual:1,    note:"TOR @ DET — 1 hit, WIN +$71.43"},
      {player:"Caleb Durbin",     prop:"H OVER 0.5",  odds:-145, tier:"T1",   hit:"void", actual:null, note:"Not in BOS lineup — VOID"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-16",
    sport: "MLB",
    plays: [
      {player:"Bryce Elder",      prop:"K OVER 4.5",  odds:-155, tier:"AUTO", hit:false, actual:3,  note:"ATL vs BOS — only 3 Ks in 8 IP, well short"},
      {player:"Aaron Judge",      prop:"TB OVER 1.5", odds:100,  tier:"T1",   hit:true,  actual:3,  note:"NYY vs NYM — 3 TB, WIN +$100"},
      {player:"Alejandro Osuna",  prop:"H OVER 0.5",  odds:-132, tier:"T1",   hit:true,  actual:1,  note:"BAL vs WSH — 1 hit, WIN +$75.76"},
      {player:"Tyrone Taylor",    prop:"H OVER 0.5",  odds:-145, tier:"T1",   hit:"void", actual:null, note:"Did not play — VOID"},
      {player:"Caleb Durbin",     prop:"H OVER 0.5",  odds:-131, tier:"T1",   hit:false, actual:0,  note:"CWS vs CHC — hitless, LOSS"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-15",
    sport: "MLB",
    plays: [
      {player:"Spencer Strider",    prop:"K OVER 6.5",  odds:-105, tier:"T1",   hit:false, actual:4,  note:"ATL vs BOS — only 4 Ks, well short of 6.5"},
      {player:"Kyle Freeland",      prop:"K OVER 3.5",  odds:118,  tier:"T2",   hit:false, actual:3,  note:"COL vs ARI — exactly 3 Ks, needed 3.5+, LOSS"},
      {player:"Marcell Ozuna",      prop:"H OVER 0.5",  odds:-118, tier:"T1",   hit:true,  actual:1,  note:"BAL vs WSH — 1 hit, WIN"},
      {player:"Aaron Judge",        prop:"TB OVER 1.5", odds:120,  tier:"T1",   hit:false, actual:1,  note:"NYY vs NYM — 1 hit, 1 TB only, LOSS"},
      {player:"Mike Trout",         prop:"H OVER 0.5",  odds:-125, tier:"T1",   hit:false, actual:0,  note:"LAD vs LAA — hitless, LOSS"},
      {player:"Colson Montgomery",  prop:"H OVER 0.5",  odds:-165, tier:"AUTO", hit:true,  actual:2,  note:"CWS vs CHC — 2 hits, WIN"},
      {player:"Bryan Reynolds",     prop:"H OVER 0.5",  odds:-190, tier:"AUTO", hit:true,  actual:2,  note:"PIT vs PHI — 2 hits, WIN"},
    ],
    parlays: [],
  },
  {
    date:  "2026-05-14",
    sport: "MLB",
    plays: [
      {player:"Nolan McLean",       prop:"K OVER 6.5",  odds:115,  tier:"T1",   hit:true,  actual:7,    note:"7.0 IP vs DET — WIN"},
      {player:"Chris Sale",         prop:"K OVER 7.5",  odds:-152, tier:"T1",   hit:true,  actual:8,    note:"6.0 IP vs CHC — WIN"},
      {player:"Colson Montgomery",  prop:"H OVER 0.5",  odds:-150, tier:"AUTO", hit:"void",actual:null, note:"DNP"},
      {player:"Bo Bichette",        prop:"H OVER 0.5",  odds:-110, tier:"AUTO", hit:false, actual:0,    note:"0-for-4 vs DET"},
      {player:"Xander Bogaerts",    prop:"H OVER 0.5",  odds:-148, tier:"AUTO", hit:false, actual:0,    note:"0-for-3 vs MIL"},
      {player:"Nico Hoerner",       prop:"H OVER 0.5",  odds:-275, tier:"AUTO", hit:false, actual:0,    note:"0-for-3, 1 BB vs ATL"},
      {player:"Christian Walker",   prop:"H OVER 0.5",  odds:-212, tier:"T1",   hit:false, actual:0,    note:"Hitless vs SEA"},
      {player:"Seiya Suzuki",       prop:"H OVER 0.5",  odds:-169, tier:"AUTO", hit:false, actual:0,    note:"Hitless vs ATL"},
      {player:"Mickey Moniak",      prop:"H OVER 0.5",  odds:155,  tier:"T1",   hit:false, actual:0,    note:"0-for-3, 1 BB vs PIT"},
      {player:"Ryan Jeffers",       prop:"H OVER 0.5",  odds:-142, tier:"T1",   hit:false, actual:0,    note:"Hitless vs MIA"},
      {player:"Miguel Vargas",      prop:"H OVER 0.5",  odds:-160, tier:"AUTO", hit:true,  actual:1,    note:"Single vs KC — WIN"},
    ],
    parlays: [
      {id:"P1", legs:"N. Hoerner + J. Naylor",               odds:"+200", hit:false, pnl:-100, note:"Juice Pair — both lost"},
      {id:"P2", legs:"C. Walker + A. Bohm",                  odds:"+200", hit:false, pnl:-100, note:"Juice Pair — Bohm lost"},
      {id:"P3", legs:"S. Suzuki + M. Vargas",                odds:"+200", hit:false, pnl:-100, note:"Value Pair — Suzuki lost"},
      {id:"P4", legs:"C. Sale + C. Montgomery",              odds:"+200", hit:true,  pnl:66,   note:"K+Hit — Montgomery voided → reduced to single +$65.79"},
      {id:"P5", legs:"X. Bogaerts + B. Bichette + M. Moniak",odds:"+200", hit:false, pnl:-100, note:"Lottery — all three lost"},
    ],
  },
  {
    date:  "2026-05-13",
    sport: "MLB",
    plays: [
      {player:"Gunnar Henderson",   prop:"H OVER 0.5",  odds:180,  tier:"T1",   hit:true,  actual:1},
      {player:"Dylan Cease",        prop:"K OVER 6.5",  odds:104,  tier:"T1",   hit:true,  actual:7},
      {player:"Mickey Moniak",      prop:"H OVER 0.5",  odds:-140, tier:"T1",   hit:true,  actual:1},
      {player:"Jacob Misiorowski",  prop:"K OVER 7.5",  odds:-144, tier:"AUTO", hit:true,  actual:8},
      {player:"Colson Montgomery",  prop:"H OVER 0.5",  odds:-167, tier:"AUTO", hit:true,  actual:1},
      {player:"Junior Caminero",    prop:"H OVER 0.5",  odds:-172, tier:"AUTO", hit:true,  actual:1},
      {player:"Miguel Vargas",      prop:"H OVER 0.5",  odds:-174, tier:"AUTO", hit:true,  actual:1},
      {player:"Tyrone Taylor",      prop:"H OVER 0.5",  odds:-150, tier:"T1",   hit:false, actual:0},
      {player:"Xander Bogaerts",    prop:"H OVER 0.5",  odds:-164, tier:"AUTO", hit:false, actual:0},
      {player:"Jonathan Aranda",    prop:"H OVER 0.5",  odds:-191, tier:"AUTO", hit:false, actual:0},
      {player:"Ernie Clement",      prop:"H OVER 0.5",  odds:-219, tier:"AUTO", hit:false, actual:0},
    ],
    parlays: [
      {id:"P1", legs:"TBD",  odds:"+200", hit:true,  pnl:200,  note:"1 parlay hit — exact legs TBD"},
      {id:"P2", legs:"TBD",  odds:"+200", hit:false, pnl:-100, note:"Loss"},
      {id:"P3", legs:"TBD",  odds:"+200", hit:false, pnl:-100, note:"Loss"},
      {id:"P4", legs:"TBD",  odds:"+200", hit:false, pnl:-100, note:"Loss"},
      {id:"P5", legs:"TBD",  odds:"+200", hit:false, pnl:-100, note:"Loss"},
      {id:"P6", legs:"TBD",  odds:"+200", hit:false, pnl:-100, note:"Loss"},
    ],
  },
  {
    date:  "2026-05-12",
    sport: "MLB",
    plays: [
      {player:"Colson Montgomery", prop:"H OVER 0.5",  odds:-237, tier:"AUTO", hit:true,  actual:"HR"},
      {player:"Aaron Judge",       prop:"H OVER 0.5",  odds:-235, tier:"T1",   hit:true,  actual:1},
      {player:"Miguel Vargas",     prop:"H OVER 0.5",  odds:-242, tier:"AUTO", hit:true,  actual:2},
      {player:"Xander Bogaerts",   prop:"H OVER 0.5",  odds:-219, tier:"AUTO", hit:true,  actual:1},
      {player:"Jonathan Aranda",   prop:"H OVER 0.5",  odds:-192, tier:"AUTO", hit:true,  actual:1},
      {player:"Bryan Reynolds",    prop:"H OVER 0.5",  odds:-260, tier:"AUTO", hit:true,  actual:1},
      {player:"Junior Caminero",   prop:"H OVER 0.5",  odds:-264, tier:"AUTO", hit:true,  actual:1},
      {player:"Mickey Moniak",     prop:"H OVER 0.5",  odds:-140, tier:"T1",   hit:true,  actual:1},
      {player:"Aaron Judge",       prop:"TB OVER 1.5", odds:-105, tier:"T1",   hit:false, actual:1},
      {player:"Zack Wheeler",      prop:"K OVER 6.5",  odds:-125, tier:"T2",   hit:false, actual:4},
      {player:"Ernie Clement",     prop:"H OVER 0.5",  odds:-213, tier:"AUTO", hit:false, actual:0},
      {player:"Bo Bichette",       prop:"H OVER 0.5",  odds:-295, tier:"AUTO", hit:false, actual:0},
      {player:"Lenyn Sosa",        prop:"H OVER 0.5",  odds:-175, tier:"AUTO", hit:false, actual:0},
      {player:"Pete Alonso",       prop:"H OVER 0.5",  odds:-184, tier:"T1",   hit:false, actual:0},
      {player:"Matt Vierling",     prop:"H OVER 0.5",  odds:-150, tier:"T1",   hit:false, actual:0},
    ],
    parlays: [
      {id:"P1", legs:"Clement + Bogaerts + Aranda",       odds:"+226", hit:false, pnl:-100, note:"Clement 0 hits — LOSS"},
      {id:"P2", legs:"Montgomery + Clement + Bogaerts",   odds:"+204", hit:false, pnl:-100, note:"Clement 0 hits — LOSS"},
      {id:"P3", legs:"Montgomery + Vargas + Aranda",      odds:"+206", hit:true,  pnl:206,  note:"All 3 hit — WIN 🎉"},
      {id:"P4", legs:"Aranda + Judge TB",                 odds:"+197", hit:false, pnl:-100, note:"Judge 1 TB missed — LOSS"},
      {id:"P5", legs:"Sosa + Vierling + Moniak",          odds:"+349", hit:false, pnl:-100, note:"Sosa + Vierling 0 hits — LOSS"},
    ],
  },
  {
    date:  "2026-05-11",
    sport: "MLB",
    plays: [
      {player:"Kevin Gausman",   prop:"K OVER 4.5",  odds:-158, tier:"T2",   hit:true,   actual:5},
      {player:"Jonathan Aranda", prop:"H OVER 0.5",  odds:-224, tier:"AUTO", hit:true,   actual:2},
      {player:"Junior Caminero", prop:"H OVER 0.5",  odds:-247, tier:"AUTO", hit:true,   actual:1},
      {player:"Aaron Judge",     prop:"H OVER 0.5",  odds:-250, tier:"T1",   hit:true,   actual:1},
      {player:"Aaron Judge",     prop:"TB OVER 1.5", odds:-110, tier:"T1",   hit:true,   actual:2},
      {player:"Lenyn Sosa",      prop:"H OVER 0.5",  odds:-175, tier:"AUTO", hit:"void", actual:null},
      {player:"Ernie Clement",   prop:"H OVER 0.5",  odds:-213, tier:"AUTO", hit:false,  actual:0},
      {player:"Pete Alonso",     prop:"H OVER 0.5",  odds:-155, tier:"T1",   hit:false,  actual:0},
      {player:"Gunnar Henderson",prop:"H OVER 0.5",  odds:-175, tier:"T1",   hit:false,  actual:0},
    ],
    parlays: [
      {id:"P1", legs:"Clement + Aranda + Sosa",      odds:"+234", hit:false, pnl:-100, note:"Clement missed, Sosa voided → LOSS"},
      {id:"P2", legs:"Clement + Sosa + Alonso",      odds:"+280", hit:false, pnl:-100, note:"Clement + Alonso missed → LOSS"},
      {id:"P3", legs:"Alonso + Judge TB",            odds:"+214", hit:false, pnl:-100, note:"Alonso missed → LOSS"},
      {id:"P4", legs:"Aranda + Caminero + Judge TB", odds:"+288", hit:true,  pnl:88,   note:"WIN 🎉 — net after 3 losses: -$12"},
    ],
  },
  {
    date:  "2026-05-10",
    sport: "MLB",
    plays: [
      {player:"Bryce Elder",       prop:"K OVER 4.5",  odds:-136, tier:"AUTO", hit:true,  actual:8},
      {player:"Noah Cameron",      prop:"K OVER 4.5",  odds:-144, tier:"AUTO", hit:false, actual:4},
      {player:"Logan Henderson",   prop:"K OVER 5.5",  odds:-156, tier:"T2",   hit:false, actual:5},
      {player:"Ernie Clement",     prop:"H OVER 0.5",  odds:-187, tier:"AUTO", hit:true,  actual:1},
      {player:"Nico Hoerner",      prop:"H OVER 0.5",  odds:-235, tier:"AUTO", hit:true,  actual:2},
      {player:"Miguel Vargas",     prop:"H OVER 0.5",  odds:-195, tier:"AUTO", hit:true,  actual:1},
      {player:"Jonathan Aranda",   prop:"H OVER 0.5",  odds:-200, tier:"AUTO", hit:true,  actual:1},
      {player:"Xander Bogaerts",   prop:"H OVER 0.5",  odds:-218, tier:"AUTO", hit:true,  actual:2},
      {player:"Rafael Devers",     prop:"H OVER 0.5",  odds:-162, tier:"AUTO", hit:true,  actual:2},
      {player:"Aaron Judge",       prop:"H OVER 0.5",  odds:-212, tier:"T1",   hit:true,  actual:1},
      {player:"Aaron Judge",       prop:"TB OVER 1.5", odds:105,  tier:"T1",   hit:true,  actual:4},
      {player:"Colson Montgomery", prop:"H OVER 0.5",  odds:-155, tier:"AUTO", hit:false, actual:0},
      {player:"Brendan Donovan",   prop:"H OVER 0.5",  odds:-250, tier:"AUTO", hit:false, actual:0},
    ],
    parlays: [
      {id:"P1", legs:"Montgomery + Clement + Vargas",  odds:"+282", hit:false, pnl:-100, note:"Montgomery 0 hits — LOSS"},
      {id:"P2", legs:"Montgomery + Donovan + Elder",   odds:"+300", hit:false, pnl:-100, note:"Montgomery + Donovan missed — LOSS"},
      {id:"P3", legs:"Montgomery + Clement + Aranda",  odds:"+279", hit:false, pnl:-100, note:"Montgomery 0 hits — LOSS"},
      {id:"P4", legs:"Clement + Aranda + Elder",       odds:"+299", hit:true,  pnl:99,   note:"WIN 🎉 — net after 3 losses: -$1"},
    ],
  },
  {
    date:  "2026-05-09",
    sport: "MLB",
    plays: [
      {player:"Colson Montgomery", prop:"H OVER 0.5",  odds:-175, tier:"AUTO", hit:true,   actual:1},
      {player:"Ernie Clement",     prop:"H OVER 0.5",  odds:-235, tier:"AUTO", hit:true,   actual:1},
      {player:"Miguel Vargas",     prop:"H OVER 0.5",  odds:-175, tier:"AUTO", hit:true,   actual:1},
      {player:"Cam Schlittler",    prop:"K OVER 5.5",  odds:100,  tier:"T2",   hit:true,   actual:6},
      {player:"Joe Ryan",          prop:"K OVER 4.5",  odds:-142, tier:"T2",   hit:true,   actual:5},
      {player:"Edward Cabrera",    prop:"K OVER 5.5",  odds:104,  tier:"T2",   hit:true,   actual:6},
      {player:"Ketel Marte",       prop:"H OVER 0.5",  odds:-250, tier:"AUTO", hit:true,   actual:1},
      {player:"Addison Barger",    prop:"TB OVER 1.5", odds:135,  tier:"AUTO", hit:false,  actual:0},
      {player:"Nico Hoerner",      prop:"H OVER 0.5",  odds:-275, tier:"AUTO", hit:false,  actual:0},
      {player:"Aaron Judge",       prop:"TB OVER 1.5", odds:117,  tier:"T1",   hit:false,  actual:0},
      {player:"Xander Bogaerts",   prop:"H OVER 0.5",  odds:-250, tier:"AUTO", hit:false,  actual:0},
      {player:"Jonathan Aranda",   prop:"H OVER 0.5",  odds:-149, tier:"AUTO", hit:"void", actual:null},
      {player:"Brendan Donovan",   prop:"H OVER 0.5",  odds:-190, tier:"AUTO", hit:"void", actual:null},
    ],
    parlays: [
      {id:"P1", legs:"Montgomery + Donovan + Vargas", odds:"+277", hit:true,  pnl:277,  note:"Donovan voided → 2-leg HIT"},
      {id:"P2", legs:"Montgomery + Clement + Aranda", odds:"+274", hit:true,  pnl:274,  note:"Aranda voided → 2-leg HIT"},
      {id:"P3", legs:"Aranda + Barger TB",            odds:"+293", hit:false, pnl:-100, note:"Barger TB missed"},
      {id:"P4", legs:"Clement + Judge TB",            odds:"+240", hit:false, pnl:-100, note:"Judge 3 walks = 0 TB"},
    ],
  },
  {
    date:  "2026-05-08",
    sport: "MLB",
    plays: [
      {player:"Kyle Bradish",   prop:"K OVER 5.5",  odds:-114, tier:"T1",   hit:true,  actual:7},
      {player:"Connelly Early", prop:"K OVER 4.5",  odds:105,  tier:"T1",   hit:true,  actual:6},
      {player:"Jacob Lopez",    prop:"K OVER 4.5",  odds:-135, tier:"T2",   hit:true,  actual:5},
      {player:"Max Fried",      prop:"K OVER 5.5",  odds:-120, tier:"T2",   hit:false, actual:5},
    ],
    parlays: [],
  },
];

export const LEGACY_FADE_RESULTS = [
  {
    date: "2026-05-22",
    sport: "MLB",
    fades: [
      {player:"Blake Perkins",  team:"MIL", prop:"H UNDER 0.5", odds:110, l14:".091", hit:true,  actual:0, note:"0 hits — WIN +$110"},
      {player:"Caleb Durbin",   team:"BOS", prop:"H UNDER 0.5", odds:110, l14:".091", hit:true,  actual:0, note:"0 hits — WIN +$110"},
      {player:"Colt Emerson",   team:"SEA", prop:"H UNDER 0.5", odds:110, l14:".091", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Adolis Garcia",  team:"PHI", prop:"H UNDER 0.5", odds:120, l14:".075", hit:true,  actual:0, note:"0 hits — WIN +$120"},
      {player:"Henry Davis",    team:"PIT", prop:"H UNDER 0.5", odds:110, l14:".095", hit:false, actual:7, note:"7 ABs, got a hit — LOSS -$100"},
    ],
  },
  {
    date: "2026-05-21",
    sport: "MLB",
    fades: [
      {player:"MJ Melendez",  team:"NYM", prop:"H UNDER 0.5", odds:129,  l14:".042", hit:true,  actual:0, note:"0 hits — WIN +$129"},
      {player:"Henry Davis",  team:"PIT", prop:"H UNDER 0.5", odds:110,  l14:".053", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Austin Wells", team:"NYY", prop:"H UNDER 0.5", odds:110,  l14:".071", hit:"void", actual:null, note:"Not in lineup — VOID"},
      {player:"Jahmai Jones", team:"DET", prop:"H UNDER 0.5", odds:118,  l14:".077", hit:true,  actual:0, note:"0 hits — WIN +$118"},
      {player:"Zack Short",   team:"DET", prop:"H UNDER 0.5", odds:110,  l14:".083", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Lenyn Sosa",   team:"TOR", prop:"H UNDER 0.5", odds:146,  l14:".095", hit:true,  actual:0, note:"0 hits — WIN +$146"},
    ],
  },
  {
    date: "2026-05-20",
    sport: "MLB",
    fades: [
      {player:"Victor Caratini", team:"KC",  prop:"H UNDER 0.5", odds:151,  l14:".083", hit:false, actual:2, note:"Got 2 hits — LOSS -$100"},
      {player:"Ozzie Albies",    team:"ATL", prop:"H UNDER 0.5", odds:171,  l14:".089", hit:false, actual:2, note:"Got 2 hits — LOSS -$100"},
      {player:"Edouard Julien",  team:"MIN", prop:"H UNDER 0.5", odds:146,  l14:".086", hit:true,  actual:0, note:"0 hits — WIN +$146"},
      {player:"Ha-Seong Kim",    team:"SD",  prop:"H UNDER 0.5", odds:130,  l14:".087", hit:"void", actual:null, note:"Not in lineup — VOID"},
    ],
  },
  {
    date: "2026-05-19",
    sport: "MLB",
    fades: [
      {player:"Ha-Seong Kim",  team:"SD",  prop:"H UNDER 0.5", odds:121,  l14:".053", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Manny Machado", team:"SD",  prop:"H UNDER 0.5", odds:145,  l14:".083", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Mitch Garver",  team:"SEA", prop:"H UNDER 0.5", odds:110,  l14:".077", hit:true,  actual:0, note:"0 hits — WIN +$110"},
      {player:"Logan O'Hoppe", team:"LAA", prop:"H UNDER 0.5", odds:122,  l14:".083", hit:false, actual:2, note:"Got 2 hits — LOSS -$100"},
      {player:"Nasim Nunez",   team:"WSH", prop:"H UNDER 0.5", odds:113,  l14:".086", hit:"void", actual:null, note:"Not in lineup — VOID"},
      {player:"Jacob Lopez",   team:"OAK", prop:"K UNDER 5.5", odds:-150, l14:"K",    hit:"void", actual:null, note:"K under — VOID"},
    ],
  },
  {
    date: "2026-05-18",
    sport: "MLB",
    fades: [
      {player:"Ha-Seong Kim",  team:"SD",  prop:"H UNDER 0.5", odds:121,  l14:".059", hit:true,  actual:0, note:"0 hits — WIN +$121"},
      {player:"Manny Machado", team:"SD",  prop:"H UNDER 0.5", odds:145,  l14:".080", hit:true,  actual:0, note:"0 hits — WIN +$145"},
      {player:"TJ Friedl",     team:"CIN", prop:"H UNDER 0.5", odds:110,  l14:".080", hit:true,  actual:0, note:"0 hits — WIN +$110"},
      {player:"Cam Smith",     team:"HOU", prop:"H UNDER 0.5", odds:146,  l14:".086", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Nasim Nunez",   team:"MIA", prop:"H UNDER 0.5", odds:113,  l14:".094", hit:true,  actual:0, note:"0 hits — WIN +$113"},
    ],
  },
  {
    date: "2026-05-17",
    sport: "MLB",
    fades: [
      {player:"Kevin Gausman", team:"TOR", prop:"K UNDER 5.5", odds:-108, l14:"K",    hit:true,  actual:5, note:"5 Ks — under 5.5, WIN +$92.59"},
      {player:"Manny Machado", team:"SD",  prop:"H UNDER 0.5", odds:130,  l14:".102", hit:false, actual:1, note:"Got a hit (5 AB) — LOSS -$100"},
      {player:"Matt Chapman",  team:"SF",  prop:"H UNDER 0.5", odds:140,  l14:".111", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Tyler O'Neill", team:"BAL", prop:"H UNDER 0.5", odds:138,  l14:".107", hit:false, actual:1, note:"1-for-4 — LOSS -$100"},
      {player:"Corey Seager",  team:"TEX", prop:"H UNDER 0.5", odds:162,  l14:".079", hit:"void", actual:null, note:"Not in lineup — VOID"},
      {player:"Ha-Seong Kim",  team:"SD",  prop:"H UNDER 0.5", odds:148,  l14:".059", hit:"void", actual:null, note:"Not in lineup — VOID"},
    ],
  },
  {
    date: "2026-05-16",
    sport: "MLB",
    fades: [
      {player:"Christian Walker",    team:"HOU", prop:"H UNDER 0.5", odds:138,  l14:".152", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Alec Bohm",           team:"PHI", prop:"H UNDER 0.5", odds:190,  l14:".080", hit:false, actual:2, note:"2 hits — LOSS -$100"},
      {player:"Eduardo Rodriguez",   team:"ARI", prop:"K UNDER 5.5", odds:-140, l14:"K",    hit:false, actual:6, note:"6 Ks — went OVER 5.5, LOSS -$100"},
      {player:"Sandy Alcantara",     team:"MIA", prop:"K UNDER 4.5", odds:-140, l14:"K",    hit:false, actual:6, note:"6 Ks — went OVER 4.5, LOSS -$100"},
    ],
  },
  {
    date: "2026-05-15",
    sport: "MLB",
    fades: [
      {player:"Bo Bichette",   team:"NYM", prop:"H UNDER 0.5", odds:200,  l14:".050", hit:true,  actual:0, note:"0-for-4 — WIN +$200"},
      {player:"Alec Bohm",     team:"PHI", prop:"H UNDER 0.5", odds:185,  l14:".080", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
      {player:"Aaron Nola",    team:"PHI", prop:"K UNDER 5.5", odds:-120, l14:"K",    hit:true,  actual:2, note:"Only 2 Ks — well under 5.5, WIN +$83"},
      {player:"Sean Burke",    team:"CWS", prop:"K UNDER 4.5", odds:-122, l14:"K",    hit:false, actual:5, note:"5 Ks — went over 4.5, LOSS -$100"},
      {player:"Manny Machado", team:"SD",  prop:"H UNDER 0.5", odds:115,  l14:".090", hit:true,  actual:0, note:"0 hits — WIN +$115"},
      {player:"Taylor Ward",   team:"LAA", prop:"H UNDER 0.5", odds:112,  l14:".086", hit:false, actual:1, note:"Got a hit — LOSS -$100"},
    ],
  },
  {
    date: "2026-05-14",
    sport: "MLB",
    fades: [
      {player:"Manny Machado", team:"SD",  prop:"H UNDER 0.5", odds:115,  l14:".111", hit:false, actual:1, note:"1-for-3, HR — cold streak broken"},
      {player:"Caleb Durbin",  team:"",    prop:"H UNDER 0.5", odds:130,  l14:".090", hit:false, actual:1, note:"1-for-1 — LOSS"},
      {player:"Royce Lewis",   team:"MIN", prop:"H UNDER 0.5", odds:106,  l14:".125", hit:true,  actual:0, note:"0-for-3 — WIN +$106"},
      {player:"Taylor Ward",   team:"LAA", prop:"H UNDER 0.5", odds:112,  l14:".086", hit:false, actual:1, note:"1-for-4 — LOSS"},
      {player:"Alec Bohm",     team:"PHI", prop:"H UNDER 0.5", odds:155,  l14:".080", hit:false, actual:1, note:"1-for-4 — LOSS"},
    ],
  },
  {
    date: "2026-05-13",
    sport: "MLB",
    fades: [
      {player:"Javier Sanoja",      team:"MIA", prop:"H UNDER 0.5", odds:140,  l14:".125", hit:false, actual:1, note:"RBI single 1st inning — LOSS (fabricated as win)"},
      {player:"Andres Gimenez",     team:"TOR", prop:"H UNDER 0.5", odds:130,  l14:".146", hit:false, actual:1, note:"Single to right field — LOSS (result was fabricated)"},
      {player:"Edouard Julien",     team:"MIN", prop:"H UNDER 0.5", odds:127,  l14:".115", hit:true,  actual:0, note:"+$127"},
      {player:"Moises Ballesteros", team:"CHC", prop:"H UNDER 0.5", odds:122,  l14:".057", hit:true,  actual:0, note:"+$122"},
      {player:"Manny Machado",      team:"SD",  prop:"H UNDER 0.5", odds:115,  l14:".111", hit:true,  actual:0, note:"+$115"},
      {player:"Ramon Laureano",     team:"CLE", prop:"H UNDER 0.5", odds:102,  l14:".069", hit:true,  actual:0, note:"+$102"},
      {player:"Sonny Gray",         team:"BOS", prop:"K UNDER 4.5", odds:-120, l14:"K",    hit:false, actual:5, note:"K model miss — got 5 Ks"},
    ],
  },
  {
    date: "2026-05-12",
    sport: "MLB",
    fades: [
      {player:"Manny Machado",  team:"SD",  prop:"H UNDER 0.5", odds:145,  l14:".098", hit:false, actual:1, note:"1-for-4 — LOSS (fabricated as win)"},
      {player:"Taylor Ward",    team:"LAA", prop:"H UNDER 0.5", odds:135,  l14:".086", hit:false, actual:2, note:"2-for-4 — LOSS (fabricated as win)"},
      {player:"Royce Lewis",    team:"MIN", prop:"H UNDER 0.5", odds:150,  l14:".125", hit:true,  actual:0, note:"+$150"},
      {player:"Josh Lowe",      team:"TB",  prop:"H UNDER 0.5", odds:135,  l14:".118", hit:true,  actual:0, note:"+$135"},
      {player:"Coby Mayo",      team:"BAL", prop:"H UNDER 0.5", odds:120,  l14:".118", hit:"void", actual:null, note:"Walk only, no official AB — VOID"},
      {player:"Spencer Jones",  team:"NYY", prop:"H UNDER 0.5", odds:115,  l14:".091", hit:"void", actual:null, note:"No official AB — VOID"},
    ],
  },
  {
    date: "2026-05-11",
    sport: "MLB",
    fades: [
      {player:"Taylor Ward",     team:"LAA", prop:"H UNDER 0.5", odds:109,  l14:".094", hit:true,  actual:0, note:"Cold bat confirmed — DK +109"},
      {player:"Tyler O'Neill",   team:"BAL", prop:"H UNDER 0.5", odds:145,  l14:".118", hit:true,  actual:0, note:"Cold bat confirmed — DK +145"},
      {player:"Rhys Hoskins",    team:"CLE", prop:"H UNDER 0.5", odds:-115, l14:".125", hit:true,  actual:0, note:"Cold bat confirmed"},
      {player:"Coby Mayo",       team:"BAL", prop:"H UNDER 0.5", odds:-115, l14:".094", hit:false, actual:1, note:"Hit anyway"},
      {player:"Andres Gimenez",  team:"TOR", prop:"H UNDER 0.5", odds:-115, l14:".135", hit:false, actual:2, note:"Heated up — borderline exclude"},
      {player:"Richie Palacios", team:"TB",  prop:"H UNDER 0.5", odds:130,  l14:".000", hit:false, actual:3, note:"Breakout game — plus money UNDER"},
    ],
  },
];
